version: '3'

services:
  users_api:
    build:
      context: .
      target: test
    tty: true
    depends_on:
      - postgres 

  postgres:
    image: postgres:latest
    container_name: testdb 
    environment:
      POSTGRES_DB: testdb 
      POSTGRES_USER: test 
      POSTGRES_PASSWORD: 1234 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

