apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-agent
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: datadog-agent

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: datadog-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: datadog-agent 
    spec:
      containers:
      - name: datadog-agent
        image: docker.io/datadog/agent:latest
        env:
        - name: DD_API_KEY
          value: "555c35b37ec810fddfb30ae20fd46a16"
        - name: DD_APP_KEY
          value: "df8740cdddefaee14fce3923094b45dd32efd79c"
        - name: DD_SITE
          value: "us5.datadoghq.com"
        - name: DD_APM_ENABLED
          value: "true"
        - name: DD_APM_NON_LOCAL_TRAFFIC
          value: "true"
        - name: DD_REMOTE_CONFIGURATION_ENABLED
          value: "true"
        ports:
        - protocol: TCP
          containerPort: 8126
        volumeMounts:
        - name: host 
          mountPath: "/"
#        - name: docker-sock
#          mountPath: "/var/run/docker.sock"
#          readOnly: true
#        - name: docker-containers
#          mountPath: "/var/lib/docker/containers"
#          readOnly: true
#        - name: proc
#          mountPath: "/host/proc/"
#          readOnly: true
#        - name: cgroup
#          mountPath: "/host/sys/fs/cgroup"
#          readOnly: true

      volumes:
      - name: host
        hostPath:
          path: "/"
#          type: DirectoryOrCreate
#      - name: docker-sock
#        hostPath:
#          path: "/var/run/docker.sock"
#          type: Socket 
#      - name: docker-containers
#        hostPath:
#          path: "/var/lib/docker/containers"
#          type: Directory 
#      - name: proc
#        hostPath:
#          path: "/proc/"
#          type: Directory
#      - name: cgroup
#        hostPath:
#          path: "/sys/fs/cgroup/"
#          type: Directory

---

apiVersion: v1
kind: Service
metadata:
  name: datadog-agent
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: datadog-agent
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8126
    targetPort: 8126
  selector:
    app.kubernetes.io/name: datadog-agent
