apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels: # service will match (forward) to pod under tagged `api`
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: # same as .spec.selector.matchLabels
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: api
        image: {{ .Values.api.image }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
#        livenessProbe:
#          periodSeconds: 1
#          httpGet:
#            path: /
#            port: 3000 
#        readinessProbe:
#          periodSeconds: 1
#          httpGet:
#            path: /
#            port: 3000 

