apiVersion: v1
kind: Service
metadata:
  name: users-api
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: users-api
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
    name: http
  selector: # labels to match pods
    {{- include "chart.selectorLabels" . | nindent 4 }} 

