name: CI

on:
  push:
    branches: [ main, dev ]

jobs:
  
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx coverage
    - name: Run unit tests
      run: pytest test/
      
    - name: Generate coverage reports
      run: coverage xml test/*.py src/*.py
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
      with:
        files: coverage.xml
        fail_ci_if_error: true



