name: CI

on:
  push:
    branches: [ main, dev ]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: "test"
          POSTGRES_PASSWORD: "1234"
          POSTGRES_DB: "testdb"
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx coverage
        export TEST_DB_URL="postgresql://test:1234@localhost:5432/testdb"
    - name: Run unit tests
      run: coverage run -m pytest .
      
    - name: Generate coverage reports
      run: coverage xml
     
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      
      with:
        files: coverage.xml
        fail_ci_if_error: true


