jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Find site-packages directory
      run: echo "SITE_PACKAGES_DIR=$(python -c 'import site; print(site.getsitepackages()[0])')" >> $GITHUB_ENV
    - name: Upload dependencies
      uses: actions/upload-artifact@v2
      with:
        name: dependencies
        path: ${{ env.SITE_PACKAGES_DIR }}

  unit_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Download dependencies
      uses: actions/download-artifact@v2
      with:
        name: dependencies
        path: ./dependencies
    - name: Adjust PYTHONPATH
      run: echo "PYTHONPATH=${{ github.workspace }}/dependencies" >> $GITHUB_ENV
    - name: Run unit tests
      run: pytest test/

