name: CI

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Upload dependencies
      uses: actions/upload-artifact@v2
      with:
        name: dependencies
        path: cache/dependencies 

  unit_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download dependencies
      uses: actions/download-artifact@v2
      with:
        name: dependencies
        path: cache/dependencies #
    - name: Run unit tests
      run: pytest test/
  

